### ISSUE TITLE
How binary data for the Adult income dataset is generated?

### ISSUE THREAD

**Issue by anhquan3012** [changdaeoh/FarconVAE#1]
Dear Chang,

I am trying to reproduce the paper's results. From what I see, the Adult income dataset has been transformed into binary format. Could you please advice me on how you did that, especially for numerical attributes?

Thank you so much. Your answert will be appreciated.

_Original Adult data_
![image](https://github.com/changdaeoh/FarconVAE/assets/108224462/d6a693c0-5f67-44bb-a037-f450a37d5e10)

_The data used in the project_
![image](https://github.com/changdaeoh/FarconVAE/assets/108224462/9265cf38-f04e-4f36-814d-d602549ebcce)

**Comment by changdaeoh** [comment]
Firstly I'm so sorry about my super lazy reply.
After I compute median values for each numerical value, assign 1 greater than the median and 0 otherwise.
